### ISSUE TITLE
Can we get the XML Backup file?

### ISSUE THREAD

**Issue by ruicaramalho** [KoenZomers/pfSenseAPI#1]
Can we download the file `/cf/conf/config.xml`.

That would be nice :)

If it helps the page is `/diag_backup.php`

On page [NetGate Backups](https://docs.netgate.com/pfsense/en/latest/backup/remote-backup.html) there's some examples

For CURL 
~~~~curl
$ curl -L -k --cookie cookies.txt --cookie-jar cookies.txt \
     https://192.168.1.1/diag_backup.php  \
     | grep "name='__csrf_magic'"   \
     | sed 's/.*value="\(.*\)".*/\1/' > csrf.txt
~~~~

**Comment by KoenZomers** [comment]
Sure, that should be easy to add to the tool. Let me see if I can find some time to incorporate it.

**Comment by ruicaramalho** [comment]
Thanks...

**Comment by ruicaramalho** [comment]
Hi. Any news?

**Comment by KoenZomers** [comment]
Functionality added in [v1.1.0.0](https://www.nuget.org/packages/KoenZomers.pfSense.Api/1.1.0)
